### ISSUE TITLE
404 doc.matrix.tu-dresden.de/ nicht erreichbar

### ISSUE THREAD

**Issue by felixx9** [matrix-tu-dresden-de/Dokumentation#15]
Webseite https://doc.matrix.tu-dresden.de/ offenbar offline.
Ist verlinkt auf https://matrix.tu-dresden.de/

![image](https://github.com/matrix-tu-dresden-de/Dokumentation/assets/51174875/ccc9cf0c-8198-49d4-b475-50862a0cc83e)

Auch Impressum etc. betroffen - darum auf diesem Weg.

**Comment by matrix-tu-dresden-de** [comment]
Vielen Dank für den Hinweis. Die Seiten sollten wieder erreichbar sein.
