### ISSUE TITLE
Aufnahme in DACH-Karte

### ISSUE THREAD

**Issue by jptsroh** [matrix-tu-dresden-de/Dokumentation#5]
Wenn die Anforderungen nicht so offiziell/restriktiv sind, wäre es schön, wenn wir auf die "Matrix-DACH" Karte aufgenommen werden könnten. MBM ScienceBridge GmbH ist eine 100% Tochter der Georg-August-Universität Göttingen, Stiftung öffenlichen Rechts, in Göttingen lokalisiert und arbeitet als Technologietransferdienstleister für verschiedene, ausschließlich akademische Forschungseinrichtungen in Niedersachsen (https://www.sciencebridge.de/de/wer-wir-sind).

Wir betreiben seit Februar 2020 matrix.sciencebridge.chat. User sind erreichbar unter @*:sciencebridge.chat.

**Comment by mdropp** [comment]
@jptsroh Um die Koordination bzgl. solcher Anfragen zu erleichtern, habe ich ein neues Sammelticket #6 erstellt (mal schauen wie das funktioniert). Ich bitte dich, dort noch einmal einen Kommentar zu hinterlassen. Auf diese Weise haben wir dann gleich mit euch ein Beispiel ^^ 

Ich werde dann gucken, dass ich euch zeitnah da integrieren. Anderseits steht euch auch frei ein Pull-Request mit dem eigenen Eintragung an das Repo zu stellen (natürlich nur falls möglich)
