### ISSUE TITLE
typo privacy

### ISSUE THREAD

**Issue by felixx9** [matrix-tu-dresden-de/Dokumentation#9]
typo auf https://doc.matrix.tu-dresden.de/privacy/
`
Die Betroffenen können verlangen, dass der Verantwortliche ihnen ihre personenbezogenen Daten maschinenlesbaren Format übermittelt.`

Muss eher heißen
`Die Betroffenen können verlangen, dass der Verantwortliche ihnen ihre personenbezogenen Daten in maschinenlesbarem Format übermittelt.`

**Comment by mdropp** [comment]
Danke für die Info. Haben das Typo gefixt.
